// flow-typed signature: bfb4285194d53619c3dcc622d1d50c8e
// flow-typed version: <<STUB>>/@shopify/polaris_v^1.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shopify/polaris'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shopify/polaris' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shopify/polaris/embedded' {
  declare module.exports: any;
}

declare module '@shopify/polaris/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shopify/polaris/embedded.js' {
  declare module.exports: $Exports<'@shopify/polaris/embedded'>;
}
declare module '@shopify/polaris/index.es.js' {
  declare module.exports: $Exports<'@shopify/polaris/index.es'>;
}
declare module '@shopify/polaris/index' {
  declare module.exports: $Exports<'@shopify/polaris'>;
}
declare module '@shopify/polaris/index.js' {
  declare module.exports: $Exports<'@shopify/polaris'>;
}
